### ISSUE TITLE
How to run the test project?

### ISSUE THREAD

**Issue by waynebloss** [wojtekmaj/react-calendar#444]
I cloned your repo, checked out to the latest release (`3.1.0`) and ran `yarn` in the repo root as well as in the `/test` directory.

However when I run `yarn start` in `/test` I get the following error:

```shell
/a/github/react-calendar/test/index.jsx: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/a/github/react-calendar/test/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "dirname": "/a/github/react-calendar/test",
    "ownPass": false,
    "file": {
      "request": "@babel/proposal-class-properties",
      "resolved": "/a/github/react-calendar/test/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  },
  {
    "alias": "base$1",
    "options": {
      "loose": "#__internal__@babel/preset-env__prefer-false-but-true-is-ok-if-it-prevents-an-error"
    },
    "dirname": "/a/github/react-calendar/test",
    "ownPass": false
  }
]
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/a/github/react-calendar/test/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "dirname": "/a/github/react-calendar/test",
    "ownPass": false,
    "file": {
      "request": "@babel/proposal-class-properties",
      "resolved": "/a/github/react-calendar/test/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  },
  {
    "alias": "base$1",
    "options": {
      "loose": "#__internal__@babel/preset-env__prefer-false-but-true-is-ok-if-it-prevents-an-error"
    },
    "dirname": "/a/github/react-calendar/test",
    "ownPass": false
  }
]
    at assertNoDuplicates (/a/github/react-calendar/test/node_modules/@babel/core/lib/config/config-descriptors.js:206:13)
    at createDescriptors (/a/github/react-calendar/test/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/a/github/react-calendar/test/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at /a/github/react-calendar/test/node_modules/@babel/core/lib/config/config-descriptors.js:63:53
    at cachedFunction (/a/github/react-calendar/test/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/a/github/react-calendar/test/node_modules/gensync/index.js:244:28)
    at sync (/a/github/react-calendar/test/node_modules/gensync/index.js:84:14)
    at plugins (/a/github/react-calendar/test/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/a/github/react-calendar/test/node_modules/@babel/core/lib/config/config-chain.js:383:26)
```

**Comment by waynebloss** [comment]
On the master branch, when I try to run `yarn` in `/test` it says:

```shell
Usage Error: The nearest package directory (/a/github/react-calendar/test) doesn't seem to be part of the project declared in /a/github/react-calendar.

- If the project directory is right, it might be that you forgot to list test as a workspace.
- If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project root detection.

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds]
```

**Comment by waynebloss** [comment]
I got it working in the master branch by changing `/test/package.json` to `"react-calendar": "file://../",` and then running `npm i`.

I was hoping to find some instructions for contributors to get started. Are there any?

**Comment by wojtekmaj** [comment]
Hmmm, what gets printed out on `yarn --version`?

**Comment by wojtekmaj** [comment]
Works on newest master for sure

<img width="1080" alt="obraz" src="https://user-images.githubusercontent.com/5426427/95568752-e874c800-0a24-11eb-95c2-c5f402ee1f37.png">
